"""empty message

Revision ID: 4e6681d3b44d
Revises: d0754799b888
Create Date: 2023-12-10 12:05:37.633864
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e6681d3b44d'
down_revision: Union[str, None] = '7ad8caab1fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'launch',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('details', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'mission',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'launch_publication',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('rocket_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['rocket_id'], ['launch.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'mission_publication',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('rocket_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['rocket_id'], ['mission.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission_publication')
    op.drop_table('launch_publication')
    op.drop_table('mission')
    op.drop_table('launch')
    # ### end Alembic commands ###
