"""empty message

Revision ID: 72cf37d07e15
Revises: 442756387567
Create Date: 2023-12-10 18:49:17.039675
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72cf37d07e15'
down_revision: Union[str, None] = '442756387567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'launch_publication',
        sa.Column('launch_id', sa.String(), nullable=False),
    )
    op.add_column(
        'launch_publication',
        sa.Column('media_type_id', sa.String(), nullable=False),
    )
    op.add_column(
        'launch_publication', sa.Column('ref', sa.String(), nullable=False)
    )
    op.drop_constraint(
        'launch_publication_rocket_id_fkey',
        'launch_publication',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        'launch_publication',
        'media_type',
        ['media_type_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        None,
        'launch_publication',
        'launch',
        ['launch_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_column('launch_publication', 'name')
    op.drop_column('launch_publication', 'rocket_id')
    op.add_column(
        'mission_publication',
        sa.Column('mission_id', sa.String(), nullable=False),
    )
    op.add_column(
        'mission_publication',
        sa.Column('media_type_id', sa.String(), nullable=False),
    )
    op.add_column(
        'mission_publication', sa.Column('ref', sa.String(), nullable=False)
    )
    op.drop_constraint(
        'mission_publication_rocket_id_fkey',
        'mission_publication',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        'mission_publication',
        'media_type',
        ['media_type_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        None,
        'mission_publication',
        'mission',
        ['mission_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_column('mission_publication', 'name')
    op.drop_column('mission_publication', 'rocket_id')
    op.add_column(
        'rocket_publication',
        sa.Column('media_type_id', sa.String(), nullable=False),
    )
    op.add_column(
        'rocket_publication', sa.Column('ref', sa.String(), nullable=False)
    )
    op.create_foreign_key(
        None,
        'rocket_publication',
        'media_type',
        ['media_type_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_column('rocket_publication', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rocket_publication',
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, 'rocket_publication', type_='foreignkey')
    op.drop_column('rocket_publication', 'ref')
    op.drop_column('rocket_publication', 'media_type_id')
    op.add_column(
        'mission_publication',
        sa.Column(
            'rocket_id', sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        'mission_publication',
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, 'mission_publication', type_='foreignkey')
    op.drop_constraint(None, 'mission_publication', type_='foreignkey')
    op.create_foreign_key(
        'mission_publication_rocket_id_fkey',
        'mission_publication',
        'mission',
        ['rocket_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_column('mission_publication', 'ref')
    op.drop_column('mission_publication', 'media_type_id')
    op.drop_column('mission_publication', 'mission_id')
    op.add_column(
        'launch_publication',
        sa.Column(
            'rocket_id', sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        'launch_publication',
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, 'launch_publication', type_='foreignkey')
    op.drop_constraint(None, 'launch_publication', type_='foreignkey')
    op.create_foreign_key(
        'launch_publication_rocket_id_fkey',
        'launch_publication',
        'launch',
        ['rocket_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_column('launch_publication', 'ref')
    op.drop_column('launch_publication', 'media_type_id')
    op.drop_column('launch_publication', 'launch_id')
    # ### end Alembic commands ###
