"""empty message

Revision ID: bd276a72633c
Revises: 72cf37d07e15
Create Date: 2023-12-10 19:36:53.968360
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd276a72633c'
down_revision: Union[str, None] = '72cf37d07e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'media_type', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_type', type_='unique')
    # ### end Alembic commands ###
