"""empty message

Revision ID: c33ea3a87af2
Revises: bd276a72633c
Create Date: 2023-12-11 00:01:42.362109
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c33ea3a87af2'
down_revision: Union[str, None] = 'bd276a72633c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launch', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('launch', 'name')
    # ### end Alembic commands ###
